/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stream-monitor` | `/stream-monitor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tide-conditions` | `/tide-conditions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wave-weather` | `/wave-weather`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stream-monitor` | `/stream-monitor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tide-conditions` | `/tide-conditions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wave-weather` | `/wave-weather`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stream-monitor${`?${string}` | `#${string}` | ''}` | `/stream-monitor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tide-conditions${`?${string}` | `#${string}` | ''}` | `/tide-conditions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wave-weather${`?${string}` | `#${string}` | ''}` | `/wave-weather${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stream-monitor` | `/stream-monitor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tide-conditions` | `/tide-conditions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wave-weather` | `/wave-weather`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
